Item1=input("Enter the item 1 : ")
Price1=input()
Item2=input("Enter the Item 2 : ")
Price2=input()
Item3=input("Enter the item 3 : ")
Price3=input()
Total=int(Price1)+int(Price2)+int(Price3)
print(Item1,":",Price1)
print(Item2,":",Price2)
print(Item3,":",Price3)
print(Total)
